#!/usr/bin/env python3

import os
import sys
from common import get_bars_as_text 

BRIGHTNESS_VALUE = 100
MIN_BRIGHTNESS = 50
MAX_BRIGHTNESS = 800

ICON = u"\uf185"

with open("/sys/class/backlight/intel_backlight/brightness") as f:
    brightness = int(f.read())
    changed = True
    
    if "up" in sys.argv:
        brightness += BRIGHTNESS_VALUE
    elif "down" in sys.argv:
        brightness -= BRIGHTNESS_VALUE
    else:
        changed = False

    if changed:
        if brightness < MIN_BRIGHTNESS: brightness = MIN_BRIGHTNESS
        if brightness > MAX_BRIGHTNESS: brightness = MAX_BRIGHTNESS

        f.close()
        with open("/sys/class/backlight/intel_backlight/brightness","w") as g:
            try:
                g.write(str(brightness))
            except Exception:
                pass

    percentage = ( float(brightness) / MAX_BRIGHTNESS ) * 100
    text = u"<span font='FontAwesome'> {} {}</span>".format(ICON, get_bars_as_text(percentage))
    print(text)
