#!/bin/bash

out=`free | awk '
	function ceil(valor){ 
		return (valor==int(valor)) ? int(valor) : int(valor)+1
	}
	function valify(valor){
		return (valor>=1) ? 0.9999 : valor
	}
	FNR>1 { print int(valify(ceil(10 * $3/$2)/10.1)*10); }'`
function colorize(){
	echo "<span color='$2'>$1</span>";
}

function get_word(){
	echo $1 | awk "{ print \$$2 }"
};
function symbolize(){
	echo "<span font='SexyFont'>$1</span>"
}
out1="MEM: `symbolize $(get_word "$out" 1)`"
out2="SWP: `symbolize $(get_word "$out" 2)`"
echo `colorize "$out1" \#00ffff` `colorize "$out2" \#ff00ff` a  
