#!/usr/bin/env python3

import netifaces
from common import is_valid_ipv4_address

interfaces = netifaces.interfaces()

ip_query = [netifaces.ifaddresses(iface) for iface in interfaces]

ips = []

__IGNORED = ['127.0.0.1']

for query in ip_query:
    for index in query:
        subquery = query[index]
        for item in subquery:
            if 'addr' not in item:
                continue
            if item['addr'] in __IGNORED:
                continue

            if is_valid_ipv4_address(item['addr']):
                ips.append(item['addr'])

each_syntax = "{}"
separator = " | "

line = separator.join(each_syntax.format(ip) for ip in ips)

print(line)
print(line)
print("#ccccff")
