#!/usr/bin/env python
from __future__ import print_function
import os


_SOUND_SYMBOL = "\uf028"


is_muted = "yes" in os.popen("pactl list sinks | grep Mute").read()
volume_line = os.popen("pactl list sinks | grep Volume").read()
# volume_line = "Volume: front-left: 31449 /  48% / -19.13 dB,   front-right: 32760 /  50% / -18.07 dB Base Volume: 65536 / 100% / 0.00 dB"

volume_line = volume_line.replace("\n","").split("%")
volume_line = [int(volume_line[i].split(" ")[-1]) for i in [0,1]]
volume = int( (volume_line[0] + volume_line[1])/2.0)




def get_text(volume):
    num_sticks = 6
    interval = int(100/num_sticks)

    sticks = int( (volume+interval/2)/ interval)

    return "|"*sticks + "."*(num_sticks-sticks)


    while volume > 10:
        ret[ret.index('.')] = '|'
        volume -= 10
    return ret

text = get_text(volume)


form = "<span font='FontAwesome'> {} {} </span>"

syntax = form.format(_SOUND_SYMBOL, text)

print(syntax)
print(syntax)

if is_muted:
    exit(33)
